<a href="https://colab.research.google.com/github/Sarvesh-joshi273/sarvesh/blob/main/cricketdatasetsj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import files
up=files.upload()

Saving cricket.csv to cricket.csv

In [3]:
df=pd.read_csv("cricket.csv")

In [4]:
df

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR
0,0,SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21368,86.23
1,1,V Kohli (INDIA),2008-2021,254,245,39,12169,183,59.07,13061,93.17
2,2,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39
3,3,RG Sharma (INDIA),2007-2021,227,220,32,9205,264,48.96,10354,88.90
4,4,ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20
...,...,...,...,...,...,...,...,...,...,...,...
114,114,SK Raina (INDIA),2005-2018,226,194,35,5615,116*,35.31,6005,93.50
115,115,H Masakadza (ZIM),2001-2019,209,208,4,5658,178*,27.73,7728,73.21
116,116,RB Richardson (WI),1983-1996,224,217,30,6248,122,33.41,9801,63.74
117,117,BB McCullum (NZ),2002-2016,260,228,28,6083,166,30.41,6312,96.37
118,118,Saleem Malik (PAK),1982-1999,283,256,38,7170,102,32.88,9383,76.41

In [5]:
df.head()

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR
0,0,SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21368,86.23
1,1,V Kohli (INDIA),2008-2021,254,245,39,12169,183,59.07,13061,93.17
2,2,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39
3,3,RG Sharma (INDIA),2007-2021,227,220,32,9205,264,48.96,10354,88.90
4,4,ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20

In [6]:
df.tail()

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR
114,114,SK Raina (INDIA),2005-2018,226,194,35,5615,116*,35.31,6005,93.50
115,115,H Masakadza (ZIM),2001-2019,209,208,4,5658,178*,27.73,7728,73.21
116,116,RB Richardson (WI),1983-1996,224,217,30,6248,122,33.41,9801,63.74
117,117,BB McCullum (NZ),2002-2016,260,228,28,6083,166,30.41,6312,96.37
118,118,Saleem Malik (PAK),1982-1999,283,256,38,7170,102,32.88,9383,76.41

In [7]:
df.shape

(119, 11)

In [8]:
df.columns

Index(['Unnamed: 0', 'Player', 'Span', 'Mat', 'Inns', 'NO', 'Runs', 'HS',
       'Ave', 'BF', 'SR'],
      dtype='object')

In [9]:
df.nunique()

Unnamed: 0    119
Player        119
Span           95
Mat           102
Inns           93
NO             46
Runs          119
HS             80
Ave           119
BF            119
SR            115
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  119 non-null    int64
 1   Player      119 non-null    object
 2   Span        119 non-null    object
 3   Mat         119 non-null    int64
 4   Inns        119 non-null    int64
 5   NO          119 non-null    int64
 6   Runs        119 non-null    int64
 7   HS          119 non-null    object
 8   Ave         119 non-null    float64
 9   BF          119 non-null    int64
 10  SR          119 non-null    float64
dtypes: float64(2), int64(6), object(3)
memory usage: 10.4+ KB

In [11]:
df.sample(10)

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR
98,98,KL Rahul (INDIA),2016-2021,38,37,6,1509,112,48.67,1690,89.28
55,55,Ijaz Ahmed (PAK),1986-2000,250,232,29,6564,139*,32.33,8174,80.30
45,45,IVA Richards (WI),1975-1991,187,167,24,6721,189*,47.00,7451,90.20
50,50,PA de Silva (SL),1984-2003,308,296,30,9284,145,34.90,11443,81.13
85,85,EC Joyce (ENG/IRE),2006-2018,78,77,8,2622,160*,38.00,3630,72.23
82,82,M Azharuddin (INDIA),1985-2000,334,308,54,9378,153*,36.92,12669,74.02
9,9,SC Ganguly (Asia/INDIA),1992-2007,311,300,23,11363,183,41.02,15416,73.70
62,62,SR Watson (AUS),2002-2015,190,169,27,5757,185*,40.54,6365,90.44
40,40,JM Bairstow (ENG),2011-2021,89,81,8,3498,141*,47.91,3331,105.01
70,70,Javed Miandad (PAK),1975-1996,233,218,41,7381,119*,41.70,11014,67.01

In [12]:
df.dtypes

Unnamed: 0      int64
Player         object
Span           object
Mat             int64
Inns            int64
NO              int64
Runs            int64
HS             object
Ave           float64
BF              int64
SR            float64
dtype: object

In [13]:
df.describe()

,Unnamed: 0,Mat,Inns,NO,Runs,Ave,BF,SR
count,119.000000,119.000000,119.000000,119.00000,119.000000,119.000000,119.000000,119.000000
mean,59.000000,194.672269,184.411765,21.10084,6306.890756,39.347983,7897.941176,81.262605
std,34.496377,94.879684,89.115276,15.81803,3091.187863,7.013547,3894.847910,11.402961
min,0.000000,33.000000,32.000000,1.00000,1447.000000,23.570000,1360.000000,55.930000
25%,29.500000,124.500000,120.000000,8.00000,3928.500000,34.910000,5086.000000,73.455000
50%,59.000000,190.000000,181.000000,16.00000,5964.000000,38.000000,7678.000000,79.980000
75%,88.500000,247.500000,236.500000,33.00000,8079.000000,42.450000,9780.500000,88.405000
max,118.000000,463.000000,452.000000,84.00000,18426.000000,67.000000,21368.000000,118.660000